import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {saveAttachment,saveClipboard,readReceipt,maxBytes} from '../../clipboard_attachments/store.mjs';
import {connectWorld} from '../../native_dsh/multi-life/supervisor/client.mjs';
const storage='.local/workspace/uploads/harness-chat';
export function roomStorageId(owner,room){const h=createHash('sha256').update(JSON.stringify([owner,room])).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20,32)}`;}
async function binding(roomId,write=false){const request=await connectWorld(),[self,c]=await Promise.all([request('/v1/self'),request('/v1/rooms')]),r=c.rooms.find(r=>r.room_id===roomId);if(!r||(write&&!r.access.can_send))throw Error('ATTACHMENT_ROOM_ACCESS_DENIED');return roomStorageId(self.principal.sender_id,roomId);}
const decorate=(file,room)=>({...file,url:'/api/persona.chatAttachment?'+new URLSearchParams({room_id:room,id:file.id})});
export async function uploadChatAttachment(request){const form=await request.formData(),room=form.get('room_id'),file=form.get('file'),id=await binding(room,true);if(!file||typeof file.arrayBuffer!=='function'||file.size>maxBytes)throw Error('附件须非空且不超过 128 MB');return decorate(await saveAttachment(storage,id,{name:file.name,type:file.type,bytes:Buffer.from(await file.arrayBuffer())}),room);}
export async function pasteChatAttachment(request){const {room_id}=await request.json(),id=await binding(room_id,true),v=await saveClipboard(storage,id);return {...v,files:v.files.map(f=>decorate(f,room_id))};}
export async function readChatAttachment(request){const u=new URL(request.url),room=u.searchParams.get('room_id'),id=await binding(room),file=await readReceipt(storage,id,u.searchParams.get('id'));const image=/^image\/(png|jpeg|webp|gif|bmp)$/.test(file.type)||/\.(png|jpe?g|webp|gif|bmp)$/i.test(file.name);const ext=file.name.split('.').pop().toLowerCase(),type=image?((/^image\/(png|jpeg|webp|gif|bmp)$/.test(file.type)?file.type:({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',bmp:'image/bmp'}[ext]))):'application/octet-stream';return new Response(new Uint8Array(await readFile(file.path)),{headers:{'content-type':type,'content-disposition':`${image?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(file.name)}`,'x-content-type-options':'nosniff','cache-control':'private, no-store'}});}
