import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createPhaseJournal} from './phases.mjs';
import {projectActivity,splitProgress,emitToolPhase} from './events.mjs';
import {progressInstruction,readPolicy,mountProgress} from './host.mjs';
import {mountParallelFileVersions} from '../workspace_foundation/file-operation-locks.mjs';
const root=await mkdtemp(join(tmpdir(),'persona-progress-'));
const sessionId='147c2fff-ff1a-5d20-b057-cd3ec56745fa';
const journal=createPhaseJournal(root);const handlers=new Map();
const ctx={get:name=>name==='fs'?ctx.fs:name==='personaProgressPhases'?journal:null,on:(name,fn)=>handlers.set(name,fn),effect:()=>{},
  fs:{resolve:async p=>p,processPath:p=>p}};
const run=()=>({});run.asyncObserved=async(observe,...args)=>{observe('queued');await Promise.resolve();observe('executing');return {token:'token-'+args[2]};};
const mounted=mountParallelFileVersions(ctx,run,new Set());
const exec={name:'read',agent:{session:{id:sessionId,header:{cwd:root}}},callId:'read-one',arguments:{file_path:'c:/fixture/a.txt'},signal:new AbortController().signal};
await handlers.get('tools/execute')(exec,async()=>({actual:true}));
const live=await journal.read(sessionId);
assert.deepEqual(live.events.map(e=>e.phase),['waiting-lock','waiting-before-backup','before-backup','executing','waiting-after-backup','after-backup','completed']);
await journal.flush();
const restored=await createPhaseJournal(root).read(sessionId);assert.deepEqual(restored.events,live.events);
assert.equal(restored.events.length,new Set(restored.events.map(e=>e.id)).size);
assert(restored.events.every(e=>e.contentHash.length===64&&!('arguments' in e)&&!('text' in e)));
const events=[{seq:0,time:1,type:'assistant/message',data:{turn:1,message:{content:[{type:'reasoning',text:'DO_NOT_DISPLAY'},{type:'text',text:'【进展】我先核对两个数据来源。\n最后结果：42。'}]}}}];
const projected=projectActivity(events,restored.events);assert.equal(projected.progress[0].text,'我先核对两个数据来源。');
assert(!JSON.stringify(projected).includes('DO_NOT_DISPLAY'));assert.equal(splitProgress(events[0].data.message.content[1].text).text,'最后结果：42。');
const before=restored.events.length;
emitToolPhase({...ctx,get:name=>name==='personaPrivateVault'?{isSensitive:()=>true}:journal},exec,'executing');
assert.equal((await journal.read(sessionId)).events.length,before);
const nextFailure=Object.assign(new Error('fixture'),{code:'TEST'});
await assert.rejects(handlers.get('tools/execute')({...exec,callId:'fail'},async()=>{throw nextFailure;}),e=>e===nextFailure);
assert.equal((await journal.read(sessionId)).events.at(-1).phase,'failed');assert.equal(mounted.fileAccess.owner,null);
let section;const agent={session:{ownEvents:()=>[{seq:0,type:'agent/inbox/spliced',data:{inserted:[{role:'user',source:{kind:'user'}}]}},{seq:1,type:'turn/start'},{seq:2,type:'agent/inbox/spliced',data:{inserted:[]}}]}};
mountProgress({systemPrompt:{section:p=>section=p},agents:{currentInitiator:()=>agent},get:()=>null,provide:()=>{}});
assert(section.text().includes('【进展】'));agent.session.ownEvents=()=>[{seq:0,type:'turn/start'},{seq:1,type:'agent/inbox/spliced',data:{inserted:[{role:'user',source:{kind:'schedule'}}]}}];assert.equal(section.text(),'');
assert(progressInstruction(readPolicy()).includes('同一条回复'));
console.log(JSON.stringify({passed:true,modelCalls:0,journal:root,checks:['real lock lifecycle stages','restart journal readback and unique IDs','source self-report extraction, reasoning excluded','private execution omitted','failure releases lock','user task policy, scheduled wake quiet']}));
