import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:http';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {createAvatarStore} from './index.mjs';
const {chromium}=createRequire(new URL('../../native_dsh/package.json',import.meta.url))('playwright');
const root=await mkdtemp(join(tmpdir(),'dsh-avatar-')),store=createAvatarStore(root),out=new URL('../../../reports/avatar-settings-20261006/',import.meta.url);
const dist=new URL('../../native_dsh/node_modules/@deepseek-ai/dsh-web-frontend/dist/assets/',import.meta.url);
const runtime=(await readFile(new URL('index-5SrrfWpU.js',dist),'utf8')).split('const fo=globalThis.dshDesktopBoot')[0]+'window.__fixtureReact=Ef;window.__fixtureDom=Df;';
const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{background:#17191e;color:#e8e9ed;margin:0;--color-text-primary:#e8e9ed}</style><div id="root"></div><article class="yb-message yb-user"><div class="yb-role">用户</div><div class="yb-markdown">用户消息</div></article><article class="yb-message"><div class="yb-role">人格</div><div class="yb-markdown">人格消息</div></article><script type="module">import './runtime.js';window.__ModuleLoader__={load(def){const plugin=def.factory(name=>{if(name==='react')return window.__fixtureReact;throw Error(name)});plugin.apply({effect(fn){fn()},slots:{inject(name,fn){fn()},register(options,Component){window.__fixtureDom.createRoot(document.getElementById('root')).render(window.__fixtureReact.createElement(Component));return()=>{}}}})}};const script=document.createElement('script');script.src='/client.js';document.head.append(script);</script>`;
const server=createServer(async(req,res)=>{try{res.setHeader('Cache-Control','no-store');if(req.url==='/api/persona.avatars'){res.setHeader('Content-Type','application/json');if(req.method==='GET'){res.end(JSON.stringify(await store.read()));return;}const chunks=[];for await(const chunk of req)chunks.push(chunk);const body=JSON.parse(Buffer.concat(chunks));res.end(JSON.stringify(await store.update(body.role,body.image)));return;}
if(req.url==='/runtime.js'){res.setHeader('Content-Type','text/javascript');res.end(runtime);return;}if(req.url==='/vendor-CCJJTK99.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('vendor-CCJJTK99.js',dist)));return;}if(req.url==='/client.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('./client.js',import.meta.url)));return;}res.setHeader('Content-Type','text/html');res.end(html);}catch(e){res.statusCode=400;res.end(JSON.stringify({error:e.message}));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,channel:'chrome'});const errors=[];
try{const context=await browser.newContext({viewport:{width:1280,height:850},deviceScaleFactor:1.5,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.getByRole('heading',{name:'头像',exact:true}).waitFor();
const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=80;c.height=40;const ctx=c.getContext('2d');ctx.fillStyle='#76bfa5';ctx.fillRect(0,0,80,40);return c.toDataURL('image/png')});const image=Buffer.from(png.split(',')[1],'base64');
await page.getByRole('button',{name:'选择图片'}).first().click({trial:true});await page.locator('input[type=file]').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:image});await page.getByText('已保存，聊天头像已更新',{exact:true}).waitFor();assert((await store.read()).user);assert.equal((await store.read()).persona,null);
const role=page.getByLabel('人格的头像粘贴区域',{exact:true});await role.click();await page.evaluate(async png=>{const blob=await (await fetch(png)).blob();await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);},png);await page.keyboard.press('Control+V');await page.waitForFunction(()=>document.querySelector('img[alt="人格的头像预览"]'));assert((await store.read()).persona);
assert.equal(await page.locator('.yb-user>.yb-role').evaluate(n=>getComputedStyle(n,'::before').content),'""');assert.equal(await page.locator('.yb-message:not(.yb-user)>.yb-role').evaluate(n=>getComputedStyle(n,'::before').content),'""');
await page.reload();await page.locator('img[alt="人格的头像预览"]').waitFor();assert.equal(await page.locator('.yb-avatar-preview[src]').count(),2);await page.screenshot({path:fileURLToPath(new URL('settings.png',out)),scale:'css'});
// Repeated paste and invalid input keep the two roles independent.
await page.getByLabel('你的头像粘贴区域',{exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await page.getByText('请选择或粘贴 PNG、JPG、WebP、GIF 或 BMP 图片',{exact:true}).waitFor();assert((await store.read()).user);
await page.getByRole('button',{name:'恢复默认'}).first().click();await page.waitForFunction(()=>!document.querySelector('img[alt="你的头像预览"]'));assert.equal((await store.read()).user,null);assert((await store.read()).persona);
const views=[];for(const [width,dpr]of [[1280,1],[410,1.5]]){const c=await browser.newContext({viewport:{width,height:850},deviceScaleFactor:dpr});const p=await c.newPage();await p.goto(url);await p.getByRole('heading',{name:'头像',exact:true}).waitFor();views.push(await p.evaluate(()=>({width:innerWidth,dpr:devicePixelRatio,overflow:document.documentElement.scrollWidth>innerWidth})));assert.equal(views.at(-1).overflow,false);if(width===410)await p.screenshot({path:fileURLToPath(new URL('settings-narrow.png',out)),scale:'css'});await c.close();}
assert.deepEqual(errors,[]);assert.throws(()=>store.update('other',null));assert.throws(()=>store.update('user','data:image/png;base64,abcd'));const result={passed:true,installedReactRuntime:true,isolatedStore:true,filePicker:true,realBrowserCtrlV:true,twoRolesIndependent:true,persistenceAfterReload:true,reset:true,invalidFilePreservesAvatar:true,chatAvatarStyles:true,views,pageErrors:errors,modelCalls:0,formalDesktopReload:false};await writeFile(new URL('validation.json',out),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
